### PR TITLE
Dependencies should work with RC1 now

### PR DESCRIPTION
**Pull request by saxx**
I played around to get the dependencies for all frameworks to compile on my machine, that only has RC1 installed. I don't think that any support for RC2 should break. Please let me know what you think.

### CODE REVIEW

**Comment by aelij** [comment]
Why did you change the 5.4 references? I think they should remain as is.

**Comment by saxx** [comment]
I changed it to get the entire solution to compile - it wouldn't otherwise on my machine (that has never been touched by RC2). I'm not entirely sure if it's really necessary, but I didn't think it would hurt functionality to use a slightly lower version?

**Comment by aelij** [comment]
I just don't know enough about Core versioning to say. It's not like these builds are stable and backwards compatibility is guaranteed... I'll try to compile it myself with your changes for dnxcore50 later.

**Comment by saxx** [comment]
Ok, thanks. Unfortunately I don't know enough about the .NET Core versioning myself. Only that `dnxcore50` (and maybe `dotnet5.4`?) are obsolete soon enough.

**Comment by aelij** [comment]
The package has been updated to support .NET Standard 1.3 as well as .NET 4.5.

**Pull request closed without merging**
